##Numpy

In [ ]:
#numpy save the storage managemet
#fast then python

In [2]:
import numpy as np

#create a numpy array?

In [10]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

#create an array 10 random intager?

In [35]:
#this is a function like randomint() & we use [] axis a list 
array=np.random.randint(1,100,10)
array

array([13, 29, 18, 19, 54, 74, 72, 13, 14, 84])

#create an array of elements from 10-20 ?

In [14]:
#arange() function, but it returns an array rather than a list. 
arr=np.arange(10,21)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

#create an array which contains value 5, 10 times?

In [52]:
a=np.ones(10)*5
a

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#create an array convert all even number in to zero?

In [54]:
#zero of [what will need in the changes in zero]=0 should be zero
#== will check equal to zero or not = indicates finally zero
zero=np.arange(1,11)
zero[zero%2==0]=0
zero

array([1, 0, 3, 0, 5, 0, 7, 0, 9, 0])

In [ ]:
#create 2d array but condition is all the element bet (0,1)?

In [ ]:
******************************************************
#create a one dimensional arryay convert it into 3*3 matrix?

In [75]:
matrix=np.arange(1,17)
matrix2=matrix.reshape((4,4))
print(matrix2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
#slicing rules
#variable in bracket[row,coloumn]
#matrix2 is the variable taken from previous question 

In [77]:
#perform slicing
arr1=np.arange(1,17).reshape(4,4)
arr2=matrix2[1:,1:4]
arr2

array([[ 6,  7,  8],
       [10, 11, 12],
       [14, 15, 16]])

Day2 Pratice

In [10]:
#type of int 8 bites -24
myarray=np.array([1,2,38888,4],np.int8)
myarray

<ipython-input-10-e73a086b908a>:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 38888 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)`
will give the desired result (the cast overflows).
  myarray=np.array([1,2,38888,4],np.int8)


array([  1,   2, -24,   4], dtype=int8)

In [12]:
#in double dimension it will show 1st row 2nd coloumn
myarray=np.array([[1,2,8,4]],np.int8)
myarray[0,2]

8

In [13]:
myarray[0,3]=66
myarray

array([[ 1,  2,  8, 66]], dtype=int8)